import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState, useEffect } from 'react';

export async function getServerSideProps() {
    const data = JSON.stringify({ time: new Date() });
    return { props: { data } };
}

export default function Home({ data }: { data: { time: string } }) {
    const [time, setTime] = useState<Date | null>(null);
    useEffect(() => {
        fetch('/api/time')
        .then(res => res.json())
        .then(json => setTime(new Date(json.time)));
    }, []);

  return (
    <div className={styles.container}>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
      <main className={styles.main}>
                <h1 className={styles.title}>
                Welcome to{" "}
                <a href="https://nextjs.org">
                    Next.js!{" "}
                    {time &&
                    `The time is ${time.getHours()}:${time.getMinutes()}:${time.getSeconds()}`}
                </a>
                </h1>      
      </main>
    
    </div>
    
  );
}
